export default {
    UPDATE_POSTS: "UPDATE_POSTS",
    REMOVE_POST: "REMOVE_POST",
    SET_CURRENT_POST: "SET_CURRENT_POST",
    ADD_POST: "ADD_POST",
    LOADING: "LOADING",
    ADD_FAVORITE: "ADD_FAVORITE",
    REMOVE_FAVORITE: "REMOVE_FAVORITE",
    UPDATE_FAVORITES: "UPDATE_FAVORITES",
}